# Generated by Django 5.0.6 on 2024-06-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata', '0003_alter_pdata2_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdata2',
            name='pid',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
