# Generated by Django 5.0.6 on 2024-07-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata', '0005_rename_pid_pdata2_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdata2',
            name='pid',
            field=models.IntegerField(null=True),
        ),
    ]
