# Generated by Django 5.0.6 on 2024-07-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productclick', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productclicks',
            new_name='productclickscount',
        ),
    ]
