# Generated by Django 5.0.6 on 2024-07-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productclick', '0002_rename_productclicks_productclickscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclickscount',
            name='productclick',
            field=models.IntegerField(null=True),
        ),
    ]
