# Generated by Django 5.0.6 on 2024-07-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productclick', '0003_alter_productclickscount_productclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclickscount',
            name='pid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productclickscount',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
