# Generated by Django 5.0.6 on 2024-06-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0002_alter_mydata2_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mydata2',
            new_name='mydata3',
        ),
    ]
