# Generated by Django 5.0.6 on 2024-06-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0004_pdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pdata',
        ),
    ]
