# Generated by Django 5.0.6 on 2024-06-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata2',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
