# Generated by Django 4.1.13 on 2024-08-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='number',
            field=models.IntegerField(max_length=100),
        ),
    ]
