# Generated by Django 4.1.13 on 2024-08-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_alter_mydata_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='number',
            field=models.IntegerField(),
        ),
    ]
