# Generated by Django 4.1.13 on 2024-08-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_alter_mydata_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mydata',
            new_name='test',
        ),
    ]
