# Generated by Django 5.0.6 on 2024-07-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdata', '0004_pdata2_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdata2',
            old_name='pid',
            new_name='uid',
        ),
    ]
